env:
  browser: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project: ./tsconfig.json
plugins:
  - prettier
  - "@typescript-eslint"
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
rules:
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
  linebreak-style:
    - 2
    - unix
  prettier/prettier: 2

  block-scoped-var: 2
  consistent-return: 2
  curly: 2
  default-case: 2
  dot-notation: 2
  eqeqeq: 2
  no-alert: 2
  no-console: 1
  no-else-return: 2
  no-eq-null: 2
  no-eval: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  no-implicit-coercion: 2
  no-implied-eval: 2
  no-invalid-this: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-native-reassign: 2
  no-new-wrappers: 2
  no-new: 2
  no-param-reassign: 2
  no-redeclare: 2
  no-self-compare: 2
  no-throw-literal: 2
