extends:
  - stylelint-config-standard
  - stylelint-config-recess-order
syntax: scss
rules:
  string-quotes: single
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
plugins:
  - stylelint-scss
